# Tester la fonction predict

In [1]:
import numpy as np
import pandas as pd

In [2]:
import predict_client

In [3]:
domain_features=['DAYS_BIRTH', 'CODE_GENDER_F', 'FLAG_RISKED_ORGANIZATION_TYPE', 
                 'RATIO_INCOME_TO_FAM_MEMBERS', 'FLAG_STABLE_INCOME_TYPE',
                 'EXT_SOURCE_2',
                 'AMT_ALL_SUM_MEAN', 'RATIO_ALL_SUM_DEBT_TO_INCOME', 'RATIO_ALL_SUM_OVERDUE_TO_INCOME', 'RATIO_ALL_MAX_OVERDUE_TO_INCOME']

In [4]:

# Example usage:
model_path = './model/model.pkl'  # Replace with your actual path
loaded_model = predict_client.load_model(model_path)

if loaded_model:
    # Now you can use the loaded model
    print(type(loaded_model)) # Print the type of the model for verification
    # Example: if it is a scikit-learn model, you could do:
    # predictions = loaded_model.predict(some_data)
else:
    print("Model loading failed.")

Model loaded successfully from ./model/model.pkl
<class 'sklearn.model_selection._classification_threshold.TunedThresholdClassifierCV'>


# Test unitaire

## Predict_client

In [5]:
np.zeros(10).reshape(1, -1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
X = np.zeros(10).reshape(1, -1)
print(loaded_model.predict(X))

[1]


In [7]:
loaded_model.predict_proba(X)

array([[0.41380521, 0.58619479]])

In [8]:
loaded_model.best_threshold_

0.27487563314524993

In [9]:
predict_client.predict_client(X)

Model loaded successfully from C:\Users\innov\OneDrive\git\OC-PJ7\sources\predict\model\model.pkl
<class 'sklearn.model_selection._classification_threshold.TunedThresholdClassifierCV'>


(1, 0.586194792437343, 0.27487563314524993)

In [10]:
decision, score, seuil = predict_client.predict_client(X)
print(decision, score, seuil)

Model loaded successfully from C:\Users\innov\OneDrive\git\OC-PJ7\sources\predict\model\model.pkl
<class 'sklearn.model_selection._classification_threshold.TunedThresholdClassifierCV'>
1 0.586194792437343 0.27487563314524993


## Predict_OneClient

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
predict_client.predict_Oneclient(np.zeros(10))

Model loaded successfully from C:\Users\innov\OneDrive\git\OC-PJ7\sources\predict\model\model.pkl
<class 'sklearn.model_selection._classification_threshold.TunedThresholdClassifierCV'>


(1, 58.6194792437343, 27.487563314524994)

# Inclure Score dans fichier train pour dashboard

In [31]:
data_path = 'c:/users/innov/python_venv/oc-pj7/input'
data = pd.read_csv(f'{data_path}/application_train_20250103.csv')

In [34]:
data.head()

,SK_ID_CURR,TARGET,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,...,AMT_ALL_SUM_DEBT,AMT_ALL_SUM_OVERDUE,AMT_ALL_MAX_OVERDUE,CODE_GENDER_F,CODE_GENDER_M,CODE_GENDER_XNA,AMT_ALL_SUM_MEAN,RATIO_ALL_SUM_OVERDUE_TO_INCOME,RATIO_ALL_MAX_OVERDUE_TO_INCOME,RATIO_ALL_SUM_DEBT_TO_INCOME
0,100002,1.0,N,1,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,...,214462.080,0.000,5043.645,0,1,0,116012.285000,0.00000,0.298883,1.059072
1,100003,0.0,N,0,0,270000.0,1293502.5,35698.5,1129500.0,Family,...,3370.320,0.000,0.000,1,0,0,352853.357143,0.00000,0.000000,0.012483
2,100004,0.0,Y,1,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,...,4174.785,0.000,0.000,0,1,0,69714.600000,0.00000,0.000000,0.061849
3,100006,0.0,N,1,0,135000.0,312682.5,29686.5,297000.0,Unaccompanied,...,537202.035,0.000,0.000,1,0,0,343728.900000,0.00000,0.000000,3.979274
4,100007,0.0,N,1,0,121500.0,513000.0,21865.5,513000.0,Unaccompanied,...,237519.990,29857.365,22678.785,0,1,0,163726.071429,0.24574,2.239880,1.954897


In [19]:
X = data.loc[:, domain_features].to_numpy()
decision, score, seuil = predict_client.predict_client(X)
print(len(score))
data['y_pred_proba'] = score[:, 1]
data.to_csv(f'{data_path}/application_train_20250103_pred.csv', index_label=False)

Model loaded successfully from C:\Users\innov\OneDrive\git\OC-PJ7\sources\predict\model\model.pkl
<class 'sklearn.model_selection._classification_threshold.TunedThresholdClassifierCV'>
307510


In [20]:
score[:, 1]

array([0.42674094, 0.10719407, 0.271318  , ..., 0.20554807, 0.22644994,
       0.12686529])

In [21]:
data['y_pred_proba'].head()

0    0.426741
1    0.107194
2    0.271318
3    0.165898
4    0.399671
Name: y_pred_proba, dtype: float64

In [10]:
len(decision)

10000

# Tester l'API Predict en local

In [10]:
import requests

#url = "http://localhost:8080/api/predict"  # Serveur Flask local
url = 'https://predictocpj7-1013078366791.europe-west9.run.app:8080/api/predict'  # On GCP 

domain_features=['DAYS_BIRTH', 'CODE_GENDER_F', 'FLAG_RISKED_ORGANIZATION_TYPE', 
                 'RATIO_INCOME_TO_FAM_MEMBERS', 'FLAG_STABLE_INCOME_TYPE',
                 'EXT_SOURCE_2',
                 'AMT_ALL_SUM_MEAN', 'RATIO_ALL_SUM_DEBT_TO_INCOME', 'RATIO_ALL_SUM_OVERDUE_TO_INCOME', 'RATIO_ALL_MAX_OVERDUE_TO_INCOME']

client_data = {
    'DAYS_BIRTH': -6.0, 
    'CODE_GENDER_F': 1, 
    'FLAG_RISKED_ORGANIZATION_TYPE': 1, 
    'RATIO_INCOME_TO_FAM_MEMBERS': 9999.0, 
    'FLAG_STABLE_INCOME_TYPE': 1,
    'EXT_SOURCE_2': 0.4,
    'AMT_ALL_SUM_MEAN': 10000.0, 
    'RATIO_ALL_SUM_DEBT_TO_INCOME': 0.20, 
    'RATIO_ALL_SUM_OVERDUE_TO_INCOME': 0.0, 
    'RATIO_ALL_MAX_OVERDUE_TO_INCOME': 0.0
}

response = requests.post(url, json=client_data)

if response.status_code == 200:
    print("Requête POST réussie")
    print(response.text)
    print("Contenu de la réponse :", response.json())
else:
    print("Erreur lors de la requête POST")
    print("Code de statut :", response.status_code)
    print("Contenu de la réponse :", response.text) 

ConnectTimeout: HTTPSConnectionPool(host='predictocpj7-1013078366791.europe-west9.run.app', port=8080): Max retries exceeded with url: /api/predict (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002B3233AB2B0>, 'Connection to predictocpj7-1013078366791.europe-west9.run.app timed out. (connect timeout=None)'))